name: Mathics3 (OSX)

on:
  push:
    branches: [master]
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macOS]
        python-version: ['3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Install OS dependencies
        run: |
          brew install llvm@11 tesseract
          python -m pip install --upgrade pip
      - name: Install Mathics-Scanner
        run: |
          python -m pip install Mathics-Scanner
      - name: Install Mathics3 with full Python dependencies
        run: |
          make develop-full
      - name: Test Mathics3
        run: |
          make -j3 check
